name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        sudo apt install libglfw3 libglfw3-dev
    - name: make
      run: make
    - name: check
      run: ls ./Zathura
